# Generated by Django 2.1 on 2020-02-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('odia_mark', models.IntegerField()),
                ('hindi_mark', models.IntegerField()),
                ('english_mark', models.IntegerField()),
                ('math_mark', models.IntegerField()),
                ('science_mark', models.IntegerField()),
                ('social_mark', models.IntegerField()),
            ],
        ),
    ]
